---
name: Build and Push Python Image to Google Cloud Platfor
on:
  push:
    branches:
      - master
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test
      PROJECT_ID: linux-app-astrafy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        run:
          echo '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        run: |-
          docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/linux-app-astrafy/linux-app/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/linux-app-astrafy/linux-app/$IMAGE_NAME:$GITHUB_SHA
          docker push europe-west2-docker.pkg.dev/linux-app-astrafy/linux-app/$IMAGE_NAME:latest
          docker push europe-west2-docker.pkg.dev/linux-app-astrafy/linux-app/linux-app/$IMAGE_NAME:$GITHUB_SHA
